class AppImages {
  static String boiPokaTitle = "lib/assets/images/boi_poka_title.png";
  static String wormLogo = "lib/assets/images/worm_logo.png";
  static String upsideDownWorm = "lib/assets/images/re_worm.png";
  static String splashGif = "lib/assets/gif/splash.gif";
  static String pokaGif = "lib/assets/gif/poka.gif";
  static String goAheadArrowIcon = "lib/assets/icons/icon_go.png";
  static String halfWorm = "lib/assets/images/halfworm.png";
  static String registerIcon = "lib/assets/images/registericon.png";
  static String backgroundEllipseImage = "lib/assets/images/elipse3.png";
  static String googleIcon = "lib/assets/images/google_icon.png";
  static String goodreadsIcon = "lib/assets/images/g_icon.png";
  static String facebookIcon = "lib/assets/images/f_icon.png";
  static String setPatternWorm = "lib/assets/images/set_pattern_worm.png";
  static String faceId = "lib/assets/images/face_id.png";
  static String setPattern = "lib/assets/images/set_pattern.png";
  static String allowIcon = "lib/assets/icons/allow.png";
  static String bouncyPoka = "lib/assets/images/bouncy_poka.png";
  static String nextIcon = "lib/assets/icons/nexticon.png";
  static String completed = "lib/assets/icons/complete.png";
  static String menuIcon = "lib/assets/icons/menu-icon.png";
  static String smLogo = "lib/assets/images/logo-sm.png";
  static String pokaLeftFacing = "lib/assets/images/poka-left-facing.png";
  static String libraryBottom = "lib/assets/images/library.png";
  static String analyticsBottom = "lib/assets/images/analytics.png";
  static String shareBooks = "lib/assets/images/share_books.png";
  static String booksWorms = "lib/assets/images/books_worms.png";
  static String backArrow = "lib/assets/images/left-arrow.png";
  static String moreVertical = "lib/assets/images/more-vertical.png";
  static String filter = "lib/assets/images/filter-icon-sm.png";
  static String shelffilter = "lib/assets/images/shelf_filter.png";
  static String gridfilter = "lib/assets/images/grid-filter.png";
  static String listfilter = "lib/assets/images/list-filter.png";
  static String closeIcon = "lib/assets/images/close.png";
  static String moreIconHorizontal = "lib/assets/images/more_horizontal.png";
  static String accPlus = "lib/assets/images/acc-plus.png";
  static String accMinus = "lib/assets/images/acc-minus.png";
  static String bookRow = "lib/assets/images/book-row.png";
  static String bookColumn = "lib/assets/images/book-coloumn.png";
  static String quotesIcon = "lib/assets/images/quotes.png";
  static String fictionHeart = "lib/assets/images/fiction_heart.png";
  static String arrowRight = "lib/assets/images/arrow-right.png";
  static String profileUserWhite = "lib/assets/images/user-white.png";
  static String fingerprint = "lib/assets/images/fingerprint.png";
  static String authFaceRecognition =
      "lib/assets/images/auth_face_recognization.png";
  static String leftTopCornerPoka =
      "lib/assets/images/left-top-corner-poka.png";
}
